### ISSUE TITLE
Malformed JSON error

### ISSUE THREAD

**Issue by niloofarmansoor** [magpie-ea/magpie-backend#104]
Hello,

I have a heroku server for my magpie experiments, and I want to have two different experiments on it at the moment. One of the experiments works just fine, but I have an issue with the new one that I've built on top of another magpie experiment. It works without any problems on debug mode and gives me the correct results, but as soon as I try to submit the result to my server, I get this error:

<img width="404" alt="screenshot" src="https://user-images.githubusercontent.com/44275856/108320092-f4695700-7187-11eb-8da7-dc1017e1b32a.png">

I have noticed that when I use multiple types of trial views in my experiment I get this error. If I only use the custom view or only use the textbox answer view, the results can be submitted. But otherwise, I get this error. Is there anything that I should change to fix this issue?

(This is the link to my experiment : https://github.com/niloofarmansoor/magpie-ospan)

**Comment by x-ji** [comment]
Thanks for reporting the error. I think this likely happened because in the old _magpie frontend some types of trial views push their results in different ways. @marcelklehr would it be OK for you to take a quick look and see if it's possible to unify the data shape? Thanks.

**Comment by marcelklehr** [comment]
I've taken a look at your code, @niloofarmansoor. It seems that you sometimes add a property to your results that is undefined. This causes _magpie to add the property to the list of fields for that experiment, but when submitting as JSON, undefined properties will be removed from the data (that's how JSON works), which creates an inconsistency.

I suspect the source of your undefined properties stems from these two lines: https://github.com/niloofarmansoor/magpie-ospan/blob/main/03_custom_views_templates.js#L82 If you removed them you should be fine.

**Comment by niloofarmansoor** [comment]
Thanks, @marcelklehr, unfortunately even removing these lines doesn't remove this error. Do you have any other suggestions?

**Comment by niloofarmansoor** [comment]
I set the undefined value to be replaced by the string "empty" to check which variables were undefined. I could fix the issue after doing this. Thanks for explaining what caused this so I can fix it, @marcelklehr.
