### ISSUE TITLE
Old version of Heroku deploy in the docs

### ISSUE THREAD

**Issue by twinters** [magpie-ea/magpie-backend#98]
Hi! Just wanted to give a heads-up that the [_magpie documentation for uploading to Heroku](https://magpie-ea.github.io/magpie-site/serverapp/02serverinstall.html) does not work anymore (refers to files that now have different context, and uses not working commands), and is out-of-sync with the readme instructions (which do work).
Just copying the instructions from the readme to the docs should thus fix the problem.

Have a nice day!

**Comment by twinters** [comment]
(In hindsight, I should have probably posted this issue to the [docs repo](https://github.com/magpie-ea/magpie-site/issues) instead, sorry!)

**Comment by x-ji** [comment]
Thanks a lot for reporting :) I just updated the page. Apparently the instructions were updated at https://magpie-ea.github.io/magpie-site/serverapp/deployment.html, but not https://magpie-ea.github.io/magpie-site/serverapp/02serverinstall.html, which was a new page created later. We'll probably just need to delete the previous "deployment" page and stick to the later structure.
